### ISSUE TITLE
`process.exit` usage not consistent between `onExit` and `on('exit'`

### ISSUE THREAD

**Issue by rwjblue** [stefanpenner/capture-exit#12]
Consider these three scripts:

```js
// plain-process-on-exit.js
process.on('exit', function() {
  process.exit(1);
});

process.exit(0);
```

```js
// capture-exit-process-on-exit.js
var captureExit = require('.');
captureExit.captureExit();

process.on('exit', function() {
  process.exit(1);
});

process.exit(0);
```

```js
// capture-exit-onExit.js
var captureExit = require('.');
captureExit.captureExit();

captureExit.onExit(function() {
  process.exit(1);
});

process.exit(0);
```

These scripts should have the same exit code, but they do not.

**Comment by stefanpenner** [comment]
2 seems to be in error, 1 and 3 are as expected.

**Comment by rwjblue** [comment]
Ya, I would expect the same exit code as with plain node (the first one).

**Comment by stefanpenner** [comment]
@rwjblue it appears i was running against the wrong code locally. It appears all is actually well, test confirming this coming shortly. Please review to make sure we didn't miss something.

**Comment by stefanpenner** [comment]
test that seems to demonstrate this works \w master: https://github.com/ember-cli/capture-exit/pull/13

**Comment by stefanpenner** [comment]
output is:

```
1, 1, 0
```

This was chosen to mimic a specific aspect of nodes error code handling.

```js
process.exit(0);

// => process exits \w 0
```


```js
process.on('exit', function() { });
process.exit(0);
process.exit(1);

// => process exits \w 0
```

```js
process.on('exit', function() { 
  process.exit(2);
});

process.exit(0);
process.exit(1);
// => process exits \w 2
```

## Nodes Rule:

The process.exit(code) which decides the fate of the process, is the ones who's exit code wins.

The call that decides the fate is
1. The first one called during a `process.on('exit')` handler, as long as there is at least one such call or
2. The first one, otherwise

## What rule does onExit follow?

The `onExit` handler cannot run during a `process.on('exit')` as it is impossible to schedule async work during that period, this means that all `process.exit` calls within `onExit`handlers fall into rule 2, which means they are trumped by the`process.exit` calls if there are any.

**Comment by rwjblue** [comment]
The idea that we are intentionally making `captureExit.onExit` have different semantics from `process.on('exit'` in this regard seems mega-WAT inducing to me.  Perhaps because of the naming choices?

**Comment by rwjblue** [comment]
Prior to your last comment, I would have suggested that "switching to `capture-exit` is simple" and given the instructions to "simply change your `process.on('exit', fn)`'s to `captureExit.onExit(fn)`'s".  

This advice would result in refactoring this:

```js
process.on('exit', function() {
  // imagine `someCondition` was something like
  // testems or mocha results or something
  if (someCondition) {
    process.exit(1);
  }
});
```

To:

```js
var captureExit = require('capture-exit');
captureExit.captureExit(); // ensure this is called as early as possible

captureExit.onExit(function() {
  if (someCondition) {
    process.exit(1);
  }
});
```

That is clearly not the case since it would result in the incorrect exit code (in precisely the kind of scenario that bit ember-cli's test suite)...

**Comment by stefanpenner** [comment]
I think the name may need to change to onAsyncExit or something. As what you want is not possible given how node works and the motivation of this feature. But it is totally reasonable to expect what you expected.

We could change the behavior, but are concerned deviating from the above mentioned rules.

**Comment by rwjblue** [comment]
Yeah, I guess it comes down to what the point is.  How would you suggest doing the refactor of the snippet from https://github.com/ember-cli/capture-exit/issues/12#issuecomment-265334851?   The only way I can think of to ensure my desired exit code looks pretty bizarro:

```js
var captureExit = require('capture-exit');
captureExit.captureExit(); // ensure this is called as early as possible

captureExit.onExit(function() {
  process.on('exit', function() {
    if (someCondition) {
      process.exit(1);  // I _think_ this might error?
    }
  });
});
```

Also, just to make it clear that I'm not making this use case up, [this is very similar to what we did in ember-cli that got us in trouble](https://github.com/ember-cli/ember-cli/blob/v2.9.1/tests/runner.js#L61-L64).

**Comment by stefanpenner** [comment]
@rwjblue call  `process.exit(1);` as soon as you know you want to exit. Is there a larger example to look at? 

Specifically, the following seems redundant:

```js
captureExit.onExit(function() {
  process.on('exit', function() {
    if (someCondition) {
      process.exit(1);  // I _think_ this might error?
    }
```

i believe it can be expressed as:

```js
process.on('exit', function() {
   if (someCondition) {
      process.exit(1);  // I _think_ this might error?
    }

```

**Comment by rwjblue** [comment]
We discussed more in slack.  The basic gist is that you need both things.  

An example refactor would be:

```
process.on('exit', function() {
   ensureCleanup() // this can only be sync without capture-exit
   process.exit(1);
});
```

to:

```
var captureExit = require('capture-exit');
captureExit.captureExit();

captureExit.onExit(function() {
  return ensureCleanup();
});

process.on('exit', function() {
  process.exit(1);
});
```

**Comment by stefanpenner** [comment]
@rwjblue https://github.com/ember-cli/capture-exit/issues/15#issuecomment-265341705
