### ISSUE TITLE
Fix `process.exit(); process.exit();` semantics

### ISSUE THREAD

**Issue by hjdivad** [stefanpenner/capture-exit#9]
Currently we exit with the last code; we should exit with the first to be consistent with node.

**Comment by hjdivad** [comment]
Note that there is a test for the multiple exits case but failing the code assertion does not seem to fail the test.

**Comment by rwjblue** [comment]
#11 reintroduces the original (or at least it is partially wrong).

Given a script with the following:

```js
process.on('exit', function() {
  process.exit(1);
});

process.exit(0);
```

The process should exit with a failing status code.
